"""Derive every downstream version artifact from the canonical VERSION file.

Run before builds (build_windows.ps1 calls this automatically) or after
bumping VERSION:

    python scripts/sync_version.py [--check]

--check exits non-zero if any derived file is out of sync (used by tests/CI).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from localcodeagent.version import version, version_tuple  # noqa: E402


def _numeric() -> str:
    return ".".join(str(p) for p in version_tuple())


def _rewrite(path: Path, subs: list[tuple[str, str]], check: bool) -> bool:
    text = path.read_text(encoding="utf-8")
    new = text
    for pat, repl in subs:
        new = re.sub(pat, repl, new)
    if check:
        return new == text
    if new != text:
        path.write_text(new, encoding="utf-8")
    return True


def backend_version_txt() -> str:
    v = version()
    n = version_tuple()
    return f'''# PyInstaller Windows version resource for ChatNexus.Backend.exe.
# GENERATED by scripts/sync_version.py from VERSION — do not hand-edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({n[0]}, {n[1]}, {n[2]}, {n[3]}),
    prodvers=({n[0]}, {n[1]}, {n[2]}, {n[3]}),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Afterburn25'),
         StringStruct('FileDescription', 'Nexus Core Backend'),
         StringStruct('FileVersion', '{v}'),
         StringStruct('InternalName', 'ChatNexus.Backend'),
         StringStruct('LegalCopyright', 'Nexus Core'),
         StringStruct('OriginalFilename', 'ChatNexus.Backend.exe'),
         StringStruct('ProductName', 'Nexus Core'),
         StringStruct('ProductVersion', '{v}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''


def sync(check: bool = False) -> list[str]:
    v, nv = version(), _numeric()
    out_of_sync: list[str] = []

    def record(path: Path, ok: bool) -> None:
        if not ok:
            out_of_sync.append(str(path.relative_to(ROOT)))

    # pyproject.toml
    record(ROOT / "pyproject.toml", _rewrite(
        ROOT / "pyproject.toml",
        [(r'(?m)^version = "[^"]+"', f'version = "{v}"')], check))

    # Inno Setup defaults
    record(ROOT / "installer" / "ChatNexus.iss", _rewrite(
        ROOT / "installer" / "ChatNexus.iss",
        [(r'#define AppVersion "[^"]+"', f'#define AppVersion "{v}"'),
         (r'#define AppNumericVersion "[^"]+"',
          f'#define AppNumericVersion "{nv}"')], check))

    # .NET desktop project
    record(ROOT / "desktop" / "ChatNexus.Desktop" / "ChatNexus.Desktop.csproj",
           _rewrite(
               ROOT / "desktop" / "ChatNexus.Desktop" / "ChatNexus.Desktop.csproj",
               [(r"<Version>[^<]+</Version>", f"<Version>{v}</Version>"),
                (r"<FileVersion>[^<]+</FileVersion>",
                 f"<FileVersion>{nv}</FileVersion>"),
                (r"<AssemblyVersion>[^<]+</AssemblyVersion>",
                 f"<AssemblyVersion>{nv}</AssemblyVersion>")], check))

    # PyInstaller backend version resource
    bvt = ROOT / "packaging" / "backend_version.txt"
    if check:
        if bvt.read_text(encoding="utf-8") != backend_version_txt():
            out_of_sync.append("packaging/backend_version.txt")
    else:
        bvt.write_text(backend_version_txt(), encoding="utf-8")

    # .agent/project.json version field (metadata only — not generated file)
    record(ROOT / ".agent" / "project.json", _rewrite(
        ROOT / ".agent" / "project.json",
        [(r'"version": "[^"]+"', f'"version": "{v}"')], check))

    return out_of_sync


if __name__ == "__main__":
    check = "--check" in sys.argv
    drift = sync(check=check)
    if check:
        if drift:
            print("OUT OF SYNC:", ", ".join(drift))
            sys.exit(1)
        print(f"all version artifacts match VERSION ({version()})")
    else:
        sync(check=True)
        print(f"synced all version artifacts to {version()}")
