const $=s=>document.querySelector(s);
const chat=$('#chat'),form=$('#composer'),input=$('#input'),send=$('#send'),mode=$('#mode'),activity=$('#activity');
let lastTask=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const welcomeHtml=()=>`<div class="welcome"><img src="/assets/chat-nexus-emblem.png" alt="Chat Nexus" class="welcome-logo" /><h1>Chat Nexus</h1><p>Your local AI coding partner.</p><span>Write. Refactor. Debug. Build. All on your machine.</span><div class="quick-actions"><button type="button" data-prompt="Explain the current code and architecture."><b>&lt;/&gt;</b>Explain this code</button><button type="button" data-prompt="Refactor the current code to be cleaner and easier to maintain."><b>✦</b>Refactor to be cleaner</button><button type="button" data-prompt="Add useful tests for the current code and run them."><b>▤</b>Add tests for this file</button><button type="button" data-prompt="Help me build a new feature in this project. Inspect the repository first and make a plan."><b>↗</b>Help me build a feature</button></div></div>`;
function setUtilityPanel(name){document.querySelectorAll('.utility-tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('[data-utility-panel]').forEach(x=>x.classList.toggle('active',x.dataset.utilityPanel===name));}
function addMessage(role,text){const welcome=chat.querySelector('.welcome');if(welcome)welcome.remove();const el=document.createElement('div');el.className=`message ${role}`;el.innerHTML=`<div class="role">${esc(role)}</div><div class="bubble">${esc(text)}</div>`;chat.appendChild(el);chat.scrollTop=chat.scrollHeight;}
function addRoute(route,events=[]){if(!route)return;const el=document.createElement('div');el.className='route';const switches=(events||[]).filter(x=>x.type==='switch').map(x=>`${x.from} → ${x.to}`).join(' · ');el.textContent=`${route.role} · ${route.model_id} · complexity ${route.complexity}${switches?' · '+switches:''}`;chat.appendChild(el);}
function renderHardware(h){if(!h)return 'Unknown';const gpu=(h.gpus||[]).map(g=>`${g.name}: ${g.free_vram_gb.toFixed(1)}/${g.total_vram_gb.toFixed(1)} GB VRAM free`).join('<br>');return `${esc(h.available_ram_gb?.toFixed?.(1)??'?')}/${esc(h.total_ram_gb?.toFixed?.(1)??'?')} GB RAM free${gpu?'<br>'+esc(gpu).replace(/&lt;br&gt;/g,'<br>'):''}`;}
function phaseIndex(phase){return ({planning:0,working:1,researching_failure:1,waiting_approval:1,interrupted:1,verifying:2,reviewing:3,done:4})[phase]??0;}
function renderDiff(task){const panel=$('#diffPanel');if(!panel)return;if(!task?.files_changed?.length){panel.className='empty-utility';panel.innerHTML='<div class="empty-icon">▤</div><strong>No changes yet</strong><p>When Chat Nexus changes code, affected files will appear here for review.</p>';return;}panel.className='task-card';panel.innerHTML=`<div class="task-head"><strong>Changed files</strong><span class="task-status">${esc(task.files_changed.length)} files</span></div><div class="files">${task.files_changed.map(f=>`<div>• ${esc(f)}</div>`).join('')}</div>${task.review?`<div class="review-box"><strong>Reviewer notes</strong>\n${esc(task.review)}</div>`:''}`;}
function renderTask(task){lastTask=task||null;renderDiff(task);if(!task){$('#taskPanel').innerHTML='<span class="muted">No task yet.</span>';return;}const p=phaseIndex(task.phase);const progress=Array.from({length:5},(_,i)=>`<span class="${i<=p?'active':''}"></span>`).join('');const pending=task.pending_approval;const approval=pending?`<div class="approval"><strong>Approval required</strong><div>${esc(pending.name)} · ${esc(pending.permission)}</div>${pending.detail?`<code>${esc(pending.detail)}</code>`:''}<div class="button-row"><button class="approve" data-approve="1">Approve</button><button class="deny" data-approve="0">Deny</button></div></div>`:'';const verify=(task.verification||[]).length?`<div class="verification-box"><strong>Verification</strong>\n${esc(task.verification.map(v=>`${v.name}: ${String(v.result).includes('EXIT_CODE=0')?'passed':'attention needed'}`).join('\n'))}</div>`:'';const review=task.review?`<div class="review-box"><strong>Reviewer</strong>\n${esc(task.review)}</div>`:'';const rp=task.research?.plan;const research=rp?`<div class="verification-box"><strong>Research</strong>\n${esc(rp.mode)} · ${rp.needed?'evidence needed':'local evidence sufficient'}${rp.reasons?.length?'\n'+esc(rp.reasons.join('\n')):''}</div>`:'';const recover=task.status==='interrupted'?`<button class="resume-button" data-recover="${esc(task.id)}">Resume interrupted task</button>`:'';const undo=['completed','completed_with_warnings','step_limit'].includes(task.status)&&task.files_changed?.length&&!task.reverted?`<button class="undo-button" data-undo="${esc(task.id)}">Undo this task</button>`:'';$('#taskPanel').innerHTML=`<div class="task-card"><div class="task-head"><span class="task-id">${esc(task.id)}</span><span class="task-status ${esc(task.status)}">${esc(task.status)}</span></div><div class="task-prompt">${esc(task.prompt)}</div><div class="progress">${progress}</div><div class="meta"><span>Phase</span><strong>${esc(task.phase)}</strong><span>Model</span><strong>${esc(task.model_role||'—')}</strong><span>Steps</span><strong>${esc(task.steps)}</strong><span>Files</span><strong>${esc(task.files_changed?.length||0)}</strong></div>${task.files_changed?.length?`<div class="files">${esc(task.files_changed.join(', '))}</div>`:''}${approval}${research}${verify}${review}${recover}${undo}</div>`;if(task.pending_approval||task.status==='interrupted')setUtilityPanel('tasks');}
function renderRecent(tasks){$('#recentTasks').innerHTML=tasks?.length?tasks.map(t=>`<div class="recent-task"><div class="row"><span>${esc((t.prompt||'').slice(0,45))}</span><span class="task-status ${esc(t.status)}">${esc(t.status)}</span></div><small>${esc(t.model_role||'')} · ${esc(t.files_changed?.length||0)} files</small></div>`).join(''):'<span class="muted">No task history.</span>';}
function renderStatus(s){$('#status').textContent=`v${s.version} · GPU ready`;$('#workspace').textContent=s.workspace;$('#hardware').innerHTML=renderHardware(s.runtime?.hardware);const statuses=Object.fromEntries((s.runtime?.statuses||[]).map(x=>[x.model_id,x]));$('#models').innerHTML=(s.models||[]).map(m=>{const r=statuses[m.id]||{};const cls=r.healthy?'healthy':r.state==='loading'?'loading':String(r.state||'').includes('error')?'error':'';const action=m.runtime==='llama_cpp'?`<button class="mini-button runtime-action" data-action="${r.healthy?'stop':'start'}" data-model="${esc(m.id)}">${r.healthy?'Stop':'Start'}</button>`:'';return `<div class="model"><div class="model-head"><strong>${esc(m.id)}</strong><span class="state ${cls}">${esc(r.state||m.runtime)}</span></div><small>${esc(m.roles.join(', '))}</small><small>${esc(m.runtime)}${r.pid?' · PID '+esc(r.pid):''}</small>${action}</div>`;}).join('');const inventory=s.runtime?.inventory||[];$('#inventory').innerHTML=inventory.length?inventory.map(x=>`<div>${esc(x.name)} <small>${esc(x.size_gb)} GB</small></div>`).join(''):'<span class="muted">No .gguf files found</span>';const idx=s.repository_index||{};$('#repoIndex').textContent=`${idx.file_count||0} files indexed${idx.generated_at?' · '+new Date(idx.generated_at*1000).toLocaleTimeString():''}`;renderTask(s.tasks?.current);renderRecent(s.tasks?.recent||[]);}
function formatBytes(value){const n=Number(value||0);if(n>=1024**3)return `${(n/1024**3).toFixed(1)} GB`;if(n>=1024**2)return `${(n/1024**2).toFixed(0)} MB`;if(n>=1024)return `${(n/1024).toFixed(0)} KB`;return `${n} B`;}
function renderReadiness(r){
  const panel=$('#readinessPanel');if(!panel)return;
  const ready=!!r.ready_to_code,selfHost=!!r.self_hosting_ready;
  const state=selfHost?'Self-host ready':ready?'Ready to code':'Setup required';
  const cls=selfHost?'selfhost':ready?'ready':'setup';
  const rows=(r.models||[]).map(m=>{const ok=m.healthy||m.runnable;const detail=m.issues?.length?m.issues.join(' · '):(m.healthy?'running':'configured');return `<div class="readiness-model"><span class="readiness-dot ${ok?'ok':'bad'}"></span><div><strong>${esc(m.id)}</strong><small>${esc(m.runtime)} · ${esc(detail)}</small></div></div>`;}).join('');
  const rec=(r.recommendations||[]).map(x=>`<li>${esc(x)}</li>`).join('');
  const suggestions=(r.suggested_models||[]);
  const setup=suggestions.length&&!ready?`<div class="setup-suggestion"><strong>${suggestions.length} local GGUF setup${suggestions.length===1?'':'s'} found</strong><small>${suggestions.map(x=>`${esc(x.id)} → ${esc((x.roles||[]).join(', '))}`).join('<br>')}</small><button id="applyModelSetup" class="mini-button" type="button">Use discovered models</button></div>`:'';
  const runtime=r.runtime_install||{};const runtimeSetup=!runtime.installed?`<div class="runtime-setup"><strong>llama.cpp runtime needed</strong><small>${esc(runtime.platform||'')} · Chat Nexus will not execute installers automatically.</small>${(runtime.commands||[]).map(c=>`<button class="mini-button copy-runtime-command" data-command="${esc(c.command)}" type="button">${esc(c.label)} · Copy install command</button>`).join('')}</div>`:`<div class="runtime-found">✓ llama.cpp · ${esc(runtime.executable||'available')}</div>`;
  const activeJobs=(r.install_jobs||[]).filter(j=>!['finished','failed','cancelled'].includes(j.state));
  const jobsByModel=Object.fromEntries(activeJobs.map(j=>[j.catalog_id,j]));
  const catalog=(r.catalog||[]).map(m=>{const job=jobsByModel[m.id];const pct=job?Math.round(Number(job.progress||0)*100):0;const action=m.verified?'<span class="catalog-installed">✓ Installed</span>':m.installed?`<button class="mini-button catalog-repair" data-catalog="${esc(m.id)}">Repair / verify</button>`:`<button class="mini-button catalog-install" data-catalog="${esc(m.id)}">Install</button>`;const progress=job?`<div class="catalog-progress"><span style="width:${pct}%"></span></div><small>${esc(job.state)} · ${pct}% · ${formatBytes(job.bytes_done||0)} / ${formatBytes(job.bytes_total||0)}</small><button class="mini-button catalog-cancel" data-job="${esc(job.id)}">Cancel</button>`:'';return `<div class="catalog-card"><div class="catalog-head"><strong>${esc(m.title)}</strong><span>${m.verified?'verified':esc(m.source_type)}</span></div><small>${esc(m.size_gb)} GB · ${esc(m.license)} · ${esc((m.roles||[]).join(', '))}</small><p>${esc(m.description)}</p><p class="hardware-note">${esc(m.hardware_note)}</p>${progress||`<div class="catalog-action">${action}</div>`}</div>`;}).join('');
  const catalogPanel=(r.catalog||[]).length?`<details class="catalog-panel"><summary>Download coding models <span>${r.catalog.length}</span></summary>${catalog}</details>`:'';
  panel.innerHTML=`<div class="readiness-head ${cls}"><span>${esc(state)}</span><small>${esc((r.covered_roles||[]).join(', ')||'no active coding roles')}</small></div>${rows||'<div class="muted">No model profiles configured.</div>'}${runtimeSetup}${setup}${catalogPanel}${rec?`<ul class="readiness-recs">${rec}</ul>`:''}${r.self_hosting_tree?`<div class="selfhost-line">${selfHost?'✓':'○'} Chat Nexus self-hosting workspace</div>`:''}`;
  const v=String($('#status').textContent||'').split(' · ')[0]||'Chat Nexus';
  $('#status').textContent=`${v} · ${selfHost?'self-host ready':ready?'ready':'setup required'}`;
}
async function loadReadiness(){try{const [readyRes,catalogRes]=await Promise.all([fetch('/api/readiness'),fetch('/api/models/catalog')]);const data=await readyRes.json();if(!readyRes.ok)throw new Error(data.error||'Readiness check failed');if(catalogRes.ok){const catalog=await catalogRes.json();data.catalog=catalog.models||[];data.install_jobs=catalog.jobs||[];}renderReadiness(data);return data;}catch(e){const p=$('#readinessPanel');if(p)p.innerHTML=`<span class="state error">${esc(e.message)}</span>`;return null;}}
async function copyText(value){
  try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);}else{const t=document.createElement('textarea');t.value=value;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();}addMessage('assistant',`Copied install command: ${value}`);}catch(e){addMessage('assistant',`Could not copy command: ${e.message}`);}
}
async function startCatalogInstall(catalogId,repair=false){
  const source=document.querySelector(`[data-catalog="${CSS.escape(catalogId)}"]`);const card=source?.closest('.catalog-card');const title=card?.querySelector('strong')?.textContent||catalogId;
  if(!confirm(`${repair?'Repair/verify':'Download and install'} ${title}? Large model downloads can use significant disk space and bandwidth.`))return;
  try{const res=await fetch('/api/models/install',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({catalog_id:catalogId,repair})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Model install failed');await loadReadiness();if(data.job?.id&&!String(data.job.id).startsWith('reuse-'))pollCatalogInstall(data.job.id);}catch(e){addMessage('assistant',`Model install error: ${e.message}`);}
}
async function pollCatalogInstall(jobId){
  try{const res=await fetch(`/api/models/install/${encodeURIComponent(jobId)}`);const data=await res.json();if(!res.ok)throw new Error(data.error||'Install status failed');await loadReadiness();if(!['finished','failed','cancelled'].includes(data.job.state)){setTimeout(()=>pollCatalogInstall(jobId),1000);}else if(data.job.state==='finished'){addMessage('assistant','Coding model installed and checksum verified. You can now use “Use discovered models” to assign it to agent roles.');}else if(data.job.state==='failed'){addMessage('assistant',`Model install failed: ${data.job.error||data.job.message}`);}}catch(e){addMessage('assistant',`Model install status error: ${e.message}`);}
}
async function cancelCatalogInstall(jobId){try{const res=await fetch('/api/models/install/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:jobId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Cancel failed');await loadReadiness();}catch(e){addMessage('assistant',`Cancel error: ${e.message}`);}}
async function applySuggestedModelSetup(){
  if(!confirm('Write the discovered GGUF role assignments to your Chat Nexus config? Existing model profiles will be replaced; other settings are preserved.'))return;
  const button=$('#applyModelSetup');if(button)button.disabled=true;
  try{const res=await fetch('/api/readiness/configure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apply:true})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not save model setup');addMessage('assistant',data.message||'Model setup saved. Restart Chat Nexus.');await loadReadiness();}catch(e){addMessage('assistant',`Model setup error: ${e.message}`);}finally{const b=$('#applyModelSetup');if(b)b.disabled=false;}
}
async function loadStatus(probe=false){try{const url=probe?'/api/runtime':'/api/status';const data=await fetch(url).then(r=>r.json());if(probe){const s=await fetch('/api/status').then(r=>r.json());s.runtime=data;renderStatus(s);}else renderStatus(data);}catch(e){$('#status').textContent='Backend unavailable';}}
async function runtimeAction(action,modelId){const res=await fetch(`/api/runtime/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model_id:modelId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Runtime action failed');await loadStatus(false);}
const imageJobEls=new Map();
function imageJobActions(job){const first=(job.outputs||[])[0]||'';if(!first)return `<a class="image-action" href="/image.html">Open Image Workspace</a>`;return `<button class="image-action" data-image-action="edit" data-path="${esc(first)}">Edit</button><button class="image-action" data-image-action="variation" data-path="${esc(first)}">Variation</button><button class="image-action" data-image-action="upscale" data-path="${esc(first)}">Upscale</button><a class="image-action" href="${esc((job.output_urls||[])[0]||'#')}" download>Save</a><a class="image-action" href="/image.html">Image Workspace</a>`;}
function paintImageJob(el,job){const pct=Math.max(0,Math.min(100,Math.round(Number(job.progress||0)*100)));const imgs=(job.output_urls||[]).map(u=>`<img src="${esc(u)}" alt="Generated image">`).join('');const message=job.error_message||job.error||'';const err=message?`<div class="image-job-error">${esc(message)}</div>`:'';const tech=job.technical_details?`<details class="technical-details"><summary>Technical details</summary><pre>${esc(job.technical_details)}</pre></details>`:'';el.innerHTML=`<div class="image-job-head"><strong>${esc(job.operation||'image')}</strong><span>${esc(job.model_id||'')} · ${esc(job.state||'queued')}</span></div><div class="image-job-progress"><span style="width:${pct}%"></span></div><small>${esc(job.stage||'queued')} · ${pct}%</small>${err}${tech}${imgs?`<div class="inline-image-gallery">${imgs}</div>`:''}<div class="inline-image-actions">${imageJobActions(job)}</div>`;}
async function pollImageJob(id){const el=imageJobEls.get(id);if(!el)return;try{const res=await fetch(`/api/image/job/${encodeURIComponent(id)}`);const data=await res.json();if(!res.ok)throw new Error(data.error||'Image job lookup failed');paintImageJob(el,data.job);if(!['finished','failed','cancelled'].includes(data.job.state))setTimeout(()=>pollImageJob(id),1000);}catch(e){el.querySelector('.image-job-error')?.remove();const d=document.createElement('div');d.className='image-job-error';d.textContent=e.message;el.appendChild(d);}}
function renderImageJobs(jobs=[]){for(const job of jobs){let el=imageJobEls.get(job.id);if(!el){const wrap=document.createElement('div');wrap.className='message assistant image-result';wrap.innerHTML='<div class="role">IMAGE</div><div class="bubble image-job-card"></div>';chat.appendChild(wrap);el=wrap.querySelector('.image-job-card');imageJobEls.set(job.id,el);}paintImageJob(el,job);if(!['finished','failed','cancelled'].includes(job.state))setTimeout(()=>pollImageJob(job.id),500);}chat.scrollTop=chat.scrollHeight;}
function renderAgentResult(data,{addAssistant=true}={}){if(addAssistant)addMessage('assistant',data.content);addRoute(data.routing,data.model_events);renderImageJobs(data.image_jobs||[]);const logs=[];if(data.model_events?.length)logs.push('MODEL EVENTS\n'+data.model_events.map((x,i)=>`${i+1}. ${JSON.stringify(x)}`).join('\n'));if(data.tool_events?.length)logs.push('TOOL EVENTS\n'+data.tool_events.map((x,i)=>`${i+1}. ${x.name} ${JSON.stringify(x.arguments)}\n${x.result}`).join('\n\n'));if(logs.length){activity.textContent=logs.join('\n\n');setUtilityPanel('terminal');}renderTask(data.task);}
async function resumeTask(approved){if(!lastTask)return;send.disabled=true;try{const res=await fetch('/api/tasks/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:lastTask.id,approved})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not resume task');renderAgentResult(data);await loadStatus(false);}catch(err){addMessage('assistant',`Resume error: ${err.message}`);}finally{send.disabled=false;}}
async function recoverTask(taskId){send.disabled=true;try{addMessage('assistant','Recovering the interrupted task from its saved workspace/checkpoint state…');const res=await fetch('/api/tasks/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:taskId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not recover task');renderAgentResult(data);await loadStatus(false);}catch(err){addMessage('assistant',`Recovery error: ${err.message}`);}finally{send.disabled=false;}}
function beginAssistantStream(){
  const welcome=chat.querySelector('.welcome');if(welcome)welcome.remove();
  const wrap=document.createElement('div');wrap.className='message assistant streaming';
  wrap.innerHTML='<div class="role">assistant</div><div class="bubble">Thinking…</div>';
  chat.appendChild(wrap);chat.scrollTop=chat.scrollHeight;
  return {wrap,bubble:wrap.querySelector('.bubble'),receivedToken:false,result:null};
}
function appendLiveActivity(text){
  const existing=activity.textContent.trim();
  if(!existing||activity.querySelector('.muted'))activity.textContent='';
  activity.textContent+=(activity.textContent?'\n':'')+text;
  if(activity.textContent.length>30000)activity.textContent=activity.textContent.slice(-30000);
  setUtilityPanel('terminal');
}
function handleAgentStreamEvent(name,data,state){
  if(name==='token'){if(!state.receivedToken){state.bubble.textContent='';state.receivedToken=true;}state.bubble.textContent+=String(data.text||'');chat.scrollTop=chat.scrollHeight;return;}
  if(name==='task'&&data.task){renderTask(data.task);return;}
  if(name==='approval'){if(data.task)renderTask(data.task);setUtilityPanel('tasks');return;}
  if(name==='model'){const e=data.event||{};appendLiveActivity(`MODEL · ${e.type||'event'} · ${e.model_id||e.to||''} ${e.role||''}`.trim());return;}
  if(name==='research'){const p=data.research?.plan||data.research||{};appendLiveActivity(`RESEARCH · ${p.mode||'preflight'}${p.needed===true?' · evidence needed':''}`);return;}
  if(name==='tool'){const t=data.tool||{};appendLiveActivity(`TOOL · ${t.name||'unknown'} ${JSON.stringify(t.arguments||{})}\n${String(t.result||'').slice(-6000)}`);return;}
  if(name==='result'){state.result=data;state.bubble.textContent=String(data.content||'');state.wrap.classList.remove('streaming');chat.scrollTop=chat.scrollHeight;return;}
  if(name==='error')throw new Error(data.error||'Agent stream failed');
}
function parseSseBlock(block,state){
  const lines=block.split(/\r?\n/);let name='message';const data=[];
  for(const line of lines){if(line.startsWith('event:'))name=line.slice(6).trim();else if(line.startsWith('data:'))data.push(line.slice(5).trimStart());}
  if(!data.length)return;let payload;const raw=data.join('\n');try{payload=JSON.parse(raw);}catch{payload={text:raw};}
  handleAgentStreamEvent(name,payload,state);
}
async function streamAgent(message){
  const state=beginAssistantStream();
  const res=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({message,mode:mode.value})});
  if(!res.ok){let detail='Request failed';try{const d=await res.json();detail=d.error||detail;}catch{}throw new Error(detail);}
  if(!res.body)throw new Error('Streaming response body is unavailable in this browser.');
  const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';
  while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let split;while((split=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,split);buffer=buffer.slice(split+2);if(block.trim())parseSseBlock(block,state);}if(done)break;}
  if(buffer.trim())parseSseBlock(buffer,state);
  if(!state.result)throw new Error('Chat Nexus stream ended before a final result was received.');
  return state.result;
}
async function undoTask(taskId){if(!confirm('Restore files to their state before this task?'))return;const res=await fetch('/api/tasks/undo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:taskId})});const data=await res.json();if(!res.ok){addMessage('assistant',`Undo error: ${data.error||'failed'}`);return;}addMessage('assistant',`Restored ${data.restored.length} file(s) from the task checkpoint.`);await loadStatus(false);}
$('#taskPanel').addEventListener('click',e=>{const a=e.target.closest('[data-approve]');if(a){resumeTask(a.dataset.approve==='1');return;}const r=e.target.closest('[data-recover]');if(r){recoverTask(r.dataset.recover);return;}const u=e.target.closest('[data-undo]');if(u)undoTask(u.dataset.undo);});
$('#models').addEventListener('click',async e=>{const btn=e.target.closest('.runtime-action');if(!btn)return;btn.disabled=true;try{await runtimeAction(btn.dataset.action,btn.dataset.model);}catch(err){addMessage('assistant',`Runtime error: ${err.message}`);}finally{btn.disabled=false;}});
$('#readinessPanel').addEventListener('click',e=>{if(e.target.closest('#applyModelSetup')){applySuggestedModelSetup();return;}const copy=e.target.closest('.copy-runtime-command'),install=e.target.closest('.catalog-install'),repair=e.target.closest('.catalog-repair'),cancel=e.target.closest('.catalog-cancel');if(copy)copyText(copy.dataset.command);else if(install)startCatalogInstall(install.dataset.catalog,false);else if(repair)startCatalogInstall(repair.dataset.catalog,true);else if(cancel)cancelCatalogInstall(cancel.dataset.job);});
$('#refreshRuntime').addEventListener('click',async()=>{await loadStatus(true);await loadReadiness();});
$('#rebuildIndex').addEventListener('click',async()=>{const b=$('#rebuildIndex');b.disabled=true;try{const res=await fetch('/api/index/rebuild',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Index rebuild failed');await loadStatus(false);}catch(e){addMessage('assistant',`Index error: ${e.message}`);}finally{b.disabled=false;}});
form.addEventListener('submit',async e=>{e.preventDefault();const message=input.value.trim();if(!message)return;addMessage('user',message);input.value='';send.disabled=true;send.textContent='…';try{const data=await streamAgent(message);renderAgentResult(data,{addAssistant:false});await loadStatus(false);}catch(err){addMessage('assistant',`Error: ${err.message}`);}finally{send.disabled=false;send.textContent='↗';input.focus();}});
chat.addEventListener('click',e=>{const prompt=e.target.closest('[data-prompt]');if(prompt){input.value=prompt.dataset.prompt||'';input.focus();return;}const b=e.target.closest('[data-image-action]');if(!b)return;const p=b.dataset.path||'';const verb={edit:'Edit this image',variation:'Create a variation of this image',upscale:'Upscale this image'}[b.dataset.imageAction]||'Edit this image';input.value=`${verb}: ${p}\n`;input.focus();});
$('#newChat').addEventListener('click',async()=>{await fetch('/api/chat/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});chat.innerHTML=welcomeHtml();activity.innerHTML='<span class="muted">Tool calls, model switches, and command output will appear here.</span>';renderTask(null);input.focus();});
document.querySelectorAll('.utility-tab').forEach(btn=>btn.addEventListener('click',()=>setUtilityPanel(btn.dataset.panel)));
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit();}});
loadStatus().then(()=>loadReadiness());input.focus();
