const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let refs=[]; let latest={}; let pendingWorkflowImport=null; let pendingWorkflowImport=null;
function parseKV(text){const o={}; for(const part of String(text||'').split(',')){const [k,v]=part.split(':').map(x=>x?.trim()); if(k&&v&&!Number.isNaN(Number(v)))o[k]=Number(v);} return o;}
function parseLoras(text){return String(text||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [name,strength]=x.split(':');return {name:name.trim(),strength:strength?Number(strength):1};});}
function pathUrl(jobId,path){const name=String(path).replace(/\\/g,'/').split('/').pop();return `/api/image/output/${encodeURIComponent(jobId)}/${encodeURIComponent(name)}`;}
async function load(){const res=await fetch('/api/image'); const data=await res.json(); latest=data; render(data);}
function render(data){
  const b=data.backend||{};
  $('#imageBackend').innerHTML=`<strong>${esc(b.type||'backend')}</strong><br><span class="state ${b.healthy?'healthy':'error'}">${b.healthy?'online':'offline'}</span><br><small>${esc(b.endpoint||'')}</small>`;
  const statusById=Object.fromEntries((data.model_status||[]).map(x=>[x.id,x]));
  $('#imageModels').innerHTML=(data.models||[]).map(m=>{
    const st=statusById[m.id]||{status:'unknown',components:[],workflows:[]};
    const missing=(st.components||[]).filter(c=>c.required&&!c.ok).map(c=>c.key);
    const wfMissing=(st.workflows||[]).filter(w=>!w.exists).length;
    const wfInvalid=(st.workflows||[]).filter(w=>w.exists&&!w.valid).length;
    const workflowRows=(st.workflows||[]).map(w=>{
      const state=!w.exists?'missing':(w.valid?'ready':'invalid');
      const detail=w.exists&&!w.valid&&w.errors?.length?` title="${esc(w.errors.join('; '))}"`:'';
      return `<div class="workflow-row"${detail}><span><strong>${esc(w.operation)}</strong><small>${esc(w.name)} · <span class="workflow-state ${state}">${state}</span></small></span><button class="mini-button import-workflow" data-model="${esc(m.id)}" data-operation="${esc(w.operation)}">Import API</button></div>`;
    }).join('');
    return `<div class="model"><strong>${esc(m.id)}</strong><small>${esc(m.family)} · ${esc(m.speed_tier)} · ${esc(m.quality_tier)}</small><small>${esc((m.capabilities||[]).join(', '))}</small><div class="model-status ${esc(st.status)}">${esc(st.status)}${missing.length?' · missing '+esc(missing.join(', ')):''}${wfMissing?' · '+wfMissing+' workflow(s) missing':''}${wfInvalid?' · '+wfInvalid+' workflow(s) invalid':''}</div><div class="model-actions"><button class="mini-button install-model" data-model="${esc(m.id)}">Install missing</button><button class="mini-button remove-model" data-model="${esc(m.id)}">Remove weights</button></div><details class="workflow-details"><summary>Workflows (${(st.workflows||[]).length})</summary>${workflowRows||'<small>No workflows configured.</small>'}</details></div>`;
  }).join('')||'<span class="muted">No image models configured.</span>';
  const sel=$('#imageModel');const prev=sel.value;sel.innerHTML='<option value="auto">Auto</option>'+(data.models||[]).map(m=>`<option value="${esc(m.id)}">${esc(m.id)}</option>`).join(''); if([...sel.options].some(x=>x.value===prev))sel.value=prev;
  $('#imageInventory').innerHTML=(data.inventory||[]).map(x=>`<div>${esc(x.name)}<br><small>${esc(x.family)} · ${esc(x.size_gb)} GB</small></div>`).join('')||'<span class="muted">No local image weights discovered.</span>';
  $('#imageInstalls').innerHTML=(data.installs||[]).slice(0,8).map(j=>`<div class="install-row"><strong>${esc(j.model_id)}</strong><br><small>${esc(j.state)}${j.current_file?' · '+esc(j.current_file.split(/[\\/]/).pop()):''}${j.error?' · '+esc(j.error):''}</small><div class="bar"><span style="width:${Math.round((j.progress||0)*100)}%"></span></div></div>`).join('')||'<span class="muted">No model installs.</span>';
  $('#loraLibrary').innerHTML=(data.loras||[]).map(l=>`<div class="lora-row"><strong>${esc(l.name)}</strong><br><small>${esc(l.version||'unversioned')} · ${esc(l.size_gb)} GB · strength ${esc(l.strength)}</small></div>`).join('')||'<span class="muted">No LoRAs installed.</span>';
  $('#subjectProfiles').innerHTML=(data.profiles||[]).map(p=>`<div>${esc(p.display_name||p.id)}</div>`).join('')||'<span class="muted">No saved profiles.</span>';
  const ps=$('#subjectProfile');const pprev=ps.value;ps.innerHTML='<option value="">None</option>'+(data.profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.display_name||p.id)}</option>`).join('');if([...ps.options].some(x=>x.value===pprev))ps.value=pprev;
  renderJobs(data.jobs||[]);renderGallery(data.jobs||[]);
}
function renderJobs(jobs){$('#imageJobs').innerHTML=jobs.slice(0,12).map(j=>`<div class="image-job"><div><strong>${esc(j.operation||'image')}</strong> · ${esc(j.model_id||'')}</div><small>${esc(j.state)} · ${esc(j.stage||'')} ${j.error?'· '+esc(j.error):''}</small><div class="bar"><span style="width:${Math.round((j.progress||0)*100)}%"></span></div>${!['finished','failed','cancelled'].includes(j.state)?`<button class="mini-button cancel-job" data-job="${esc(j.id)}">Cancel</button>`:''}</div>`).join('')||'<span class="muted">No image jobs yet.</span>';}
function renderGallery(jobs){const done=jobs.filter(j=>j.state==='finished'&&j.outputs?.length);$('#imageGallery').innerHTML=done.flatMap(j=>j.outputs.map(path=>`<div class="gallery-card"><img src="${pathUrl(j.id,path)}" alt="Generated image"><div class="meta"><strong>${esc(j.model_id)}</strong><br>${esc(j.request?.prompt||'').slice(0,120)}</div><div class="actions"><button class="mini-button use-source" data-src="${esc(path)}">Edit</button><button class="mini-button reuse-job" data-job="${esc(j.id)}">Reuse settings</button></div></div>`)).join('')||'<span class="muted">Finished images appear here.</span>';}
function renderRefs(){ $('#referenceStrip').innerHTML=refs.map((r,i)=>`<div class="reference-card"><img src="${r.preview}"><button class="mini-button" data-remove-ref="${i}">Remove</button></div>`).join('');}
async function uploadFile(file){const data=await new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=fail;r.readAsDataURL(file);});const res=await fetch('/api/image/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,data_base64:data})});const out=await res.json();if(!res.ok)throw new Error(out.error||'Upload failed');refs.push({path:out.path,preview:data,name:file.name});renderRefs();}
async function submit(){const prompt=$('#imagePrompt').value.trim();if(!prompt){$('#imageStatus').textContent='Describe what you want first.';return;}const [width,height]=$('#imageResolution').value.split('x').map(Number);const seed=$('#imageSeed').value;const body={prompt,operation:$('#imageOperation').value,negative_prompt:$('#negativePrompt').value,width,height,count:Number($('#imageCount').value||1),seed:seed===''?null:Number(seed),quality:$('#imageQuality').value,reference_images:refs.map(r=>r.path),source_image:refs[0]?.path||'',subject_profile:$('#subjectProfile').value,model_override:$('#imageModel').value,loras:parseLoras($('#loras').value),outpaint:parseKV($('#outpaint').value),transparent_background:$('#transparentBg').checked,upscale:$('#upscale').checked,refine_details:$('#refineDetails').checked,real_person:$('#realPerson').checked};const steps=$('#imageSteps').value,guidance=$('#imageGuidance').value,a=$('#imageStrength').value,d=$('#denoiseStrength').value;if(steps!=='')body.steps=Number(steps);if(guidance!=='')body.guidance=Number(guidance);if(a!=='')body.image_strength=Number(a);if(d!=='')body.denoise_strength=Number(d);$('#generateImage').disabled=true;$('#imageStatus').textContent='Queueing image job…';try{const res=await fetch('/api/image/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await res.json();if(!res.ok)throw new Error(out.error||'Image request failed');$('#imageStatus').textContent=`Queued ${out.job.id.slice(0,8)} using ${out.job.model_id}`;await load();}catch(e){$('#imageStatus').textContent=e.message;}finally{$('#generateImage').disabled=false;}}
$('#dropzone').addEventListener('click',()=>$('#imageFiles').click());$('#imageFiles').addEventListener('change',async e=>{for(const f of e.target.files)await uploadFile(f);e.target.value='';});['dragenter','dragover'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();$('#dropzone').classList.add('drag');}));['dragleave','drop'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();$('#dropzone').classList.remove('drag');}));$('#dropzone').addEventListener('drop',async e=>{for(const f of e.dataTransfer.files)if(f.type.startsWith('image/'))await uploadFile(f);});$('#referenceStrip').addEventListener('click',e=>{const b=e.target.closest('[data-remove-ref]');if(b){refs.splice(Number(b.dataset.removeRef),1);renderRefs();}});$('#generateImage').addEventListener('click',submit);$('#randomSeed').addEventListener('click',()=>{$('#imageSeed').value=Math.floor(Math.random()*2147483647)});$('#refreshImages').addEventListener('click',load);$('#imageJobs').addEventListener('click',async e=>{const b=e.target.closest('.cancel-job');if(!b)return;await fetch('/api/image/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:b.dataset.job})});load();});$('#imageGallery').addEventListener('click',e=>{const r=e.target.closest('.reuse-job');if(r){const j=(latest.jobs||[]).find(x=>x.id===r.dataset.job);if(j){const q=j.request||{};$('#imagePrompt').value=q.prompt||'';$('#negativePrompt').value=q.negative_prompt||'';$('#imageQuality').value=q.quality||'balanced';$('#imageModel').value=j.model_id||'auto';$('#imageSteps').value=q.steps??'';$('#imageGuidance').value=q.guidance??'';}}});
async function postJson(url,body={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}
$('#imageModels').addEventListener('click',async e=>{const install=e.target.closest('.install-model'),remove=e.target.closest('.remove-model'),imp=e.target.closest('.import-workflow');try{if(imp){pendingWorkflowImport={model_id:imp.dataset.model,operation:imp.dataset.operation};$('#workflowFile').value='';$('#workflowFile').click();return;}if(install){install.disabled=true;await postJson('/api/image/models/install',{model_id:install.dataset.model});$('#imageStatus').textContent=`Installing ${install.dataset.model}…`;await load();}if(remove){if(!confirm(`Remove installed weight files for ${remove.dataset.model}?`))return;remove.disabled=true;const d=await postJson('/api/image/models/remove',{model_id:remove.dataset.model});$('#imageStatus').textContent=`Removed ${d.removed.length} file(s).`;await load();}}catch(err){$('#imageStatus').textContent=err.message;}finally{if(install)install.disabled=false;if(remove)remove.disabled=false;}});
$('#workflowFile').addEventListener('change',async e=>{const file=e.target.files?.[0],target=pendingWorkflowImport;pendingWorkflowImport=null;if(!file||!target)return;try{$('#imageStatus').textContent=`Validating ${file.name} for ${target.model_id} / ${target.operation}…`;const text=await file.text();let workflow;try{workflow=JSON.parse(text);}catch{throw new Error('Workflow file is not valid JSON.');}const d=await postJson('/api/image/workflows/import',{...target,workflow});$('#imageStatus').textContent=`Imported ${d.workflow.name} (${d.workflow.node_count} API nodes).`;await load();}catch(err){$('#imageStatus').textContent=err.message;}finally{e.target.value='';}});
$('#verifyImageModels').addEventListener('click',async()=>{try{$('#imageStatus').textContent='Verifying image models…';await postJson('/api/image/models/verify',{});await load();$('#imageStatus').textContent='Model verification complete.';}catch(e){$('#imageStatus').textContent=e.message;}});
$('#startImageBackend').addEventListener('click',async()=>{try{$('#imageStatus').textContent='Starting ComfyUI…';await postJson('/api/image/backend/start',{});await load();}catch(e){$('#imageStatus').textContent=e.message;}});
$('#stopImageBackend').addEventListener('click',async()=>{try{await postJson('/api/image/backend/stop',{});await load();}catch(e){$('#imageStatus').textContent=e.message;}});
load();setInterval(load,2500);
