const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let refs=[]; let latest={}; let pendingWorkflowImport=null; let maskRef=null; let maskDirty=false; let maskMode='paint'; let maskDrawing=false; let maskCtx=null;
function parseKV(text){const o={}; for(const part of String(text||'').split(',')){const [k,v]=part.split(':').map(x=>x?.trim()); if(k&&v&&!Number.isNaN(Number(v)))o[k]=Number(v);} return o;}
function parseLoras(text){return String(text||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [name,strength]=x.split(':');return {name:name.trim(),strength:strength?Number(strength):1};});}
function pathUrl(jobId,path){const name=String(path).replace(/\\/g,'/').split('/').pop();return `/api/image/output/${encodeURIComponent(jobId)}/${encodeURIComponent(name)}`;}
function setCompareImage(id,emptyId,url){const img=$(id),empty=$(emptyId);if(!img||!empty)return;if(url){img.src=url;img.classList.add('has-image');empty.style.display='none';}else{img.removeAttribute('src');img.classList.remove('has-image');empty.style.display='';}}
function updateComparison(jobs=[]){const source=refs[0]?.preview||'';setCompareImage('#beforeImage','#beforeEmpty',source);const done=[...jobs].reverse().find(j=>j.state==='finished'&&j.outputs?.length);const after=done?pathUrl(done.id,done.outputs[0]):'';setCompareImage('#afterImage','#afterEmpty',after);}
function maskState(text,kind=''){const el=$('#maskState');if(!el)return;el.textContent=text;el.className=`mask-state ${kind}`.trim();}
function initMask(preview){const canvas=$('#maskCanvas'),source=$('#maskSource'),empty=$('#maskEmpty');maskRef=null;maskDirty=false;if(!canvas||!source||!empty)return;if(!preview){canvas.classList.remove('ready');source.removeAttribute('src');empty.style.display='';maskState('No source selected');return;}const img=new Image();img.onload=()=>{canvas.width=img.naturalWidth||img.width;canvas.height=img.naturalHeight||img.height;maskCtx=canvas.getContext('2d',{willReadFrequently:true});maskCtx.fillStyle='black';maskCtx.fillRect(0,0,canvas.width,canvas.height);source.src=preview;canvas.classList.add('ready');empty.style.display='none';maskState('Mask ready','saved');};img.onerror=()=>maskState('Could not load source','dirty');img.src=preview;}
function canvasPoint(e){const c=$('#maskCanvas'),r=c.getBoundingClientRect();return {x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height),scale:c.width/r.width};}
function drawMask(e){if(!maskDrawing||!maskCtx)return;const p=canvasPoint(e),radius=Number($('#maskBrush').value||48)*p.scale;maskCtx.beginPath();maskCtx.arc(p.x,p.y,radius,0,Math.PI*2);maskCtx.fillStyle=maskMode==='erase'?'black':'white';maskCtx.fill();maskDirty=true;maskRef=null;maskState('Unsaved mask','dirty');}
function setMaskMode(mode){maskMode=mode;$('#maskPaint')?.classList.toggle('active',mode==='paint');$('#maskErase')?.classList.toggle('active',mode==='erase');}
function fillMask(color){const c=$('#maskCanvas');if(!maskCtx||!c?.width)return;maskCtx.fillStyle=color;maskCtx.fillRect(0,0,c.width,c.height);maskDirty=true;maskRef=null;maskState('Unsaved mask','dirty');}
function invertMask(){const c=$('#maskCanvas');if(!maskCtx||!c?.width)return;const image=maskCtx.getImageData(0,0,c.width,c.height),d=image.data;for(let i=0;i<d.length;i+=4){d[i]=255-d[i];d[i+1]=255-d[i+1];d[i+2]=255-d[i+2];}maskCtx.putImageData(image,0,0);maskDirty=true;maskRef=null;maskState('Unsaved mask','dirty');}
async function saveMask(){const c=$('#maskCanvas');if(!c?.width)throw new Error('Choose a source image before saving a mask.');const blob=await new Promise((ok,fail)=>c.toBlob(b=>b?ok(b):fail(new Error('Could not encode mask PNG.')),'image/png'));const data=await new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=fail;r.readAsDataURL(blob);});const res=await fetch('/api/image/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:`mask-${Date.now()}.png`,data_base64:data})});const out=await res.json();if(!res.ok)throw new Error(out.error||'Mask upload failed');maskRef={path:out.path,preview:data};maskDirty=false;maskState('Mask saved','saved');return maskRef;}
async function load(){const res=await fetch('/api/image'); const data=await res.json(); latest=data; render(data);}
function render(data){
  const b=data.backend||{};
  $('#imageBackend').innerHTML=`<strong>${esc(b.type||'backend')}</strong><br><span class="state ${b.healthy?'healthy':'error'}">${b.healthy?'online':'offline'}</span><br><small>${esc(b.endpoint||'')}</small>`;
  const statusById=Object.fromEntries((data.model_status||[]).map(x=>[x.id,x]));
  $('#imageModels').innerHTML=(data.models||[]).map(m=>{
    const st=statusById[m.id]||{status:'unknown',components:[],workflows:[]};
    const missing=(st.components||[]).filter(c=>c.required&&!c.ok).map(c=>c.key);
    const wfMissing=(st.workflows||[]).filter(w=>!w.exists).length;
    const wfInvalid=(st.workflows||[]).filter(w=>w.exists&&!w.valid).length;
    const workflowRows=(st.workflows||[]).map(w=>{
      const state=!w.exists?'missing':(w.valid?'ready':'invalid');
      const detail=w.exists&&!w.valid&&w.errors?.length?` title="${esc(w.errors.join('; '))}"`:'';
      return `<div class="workflow-row"${detail}><span><strong>${esc(w.operation)}</strong><small>${esc(w.name)} · <span class="workflow-state ${state}">${state}</span></small></span><button class="mini-button import-workflow" data-model="${esc(m.id)}" data-operation="${esc(w.operation)}">Import API</button></div>`;
    }).join('');
    return `<div class="model"><strong>${esc(m.display_name||m.id)}</strong><small>${esc(m.tagline||m.family)}${m.tagline?' · '+esc(m.family):''} · ${esc(m.speed_tier)} · ${esc(m.quality_tier)}</small><small>${esc((m.capabilities||[]).join(', '))}</small><div class="model-status ${esc(st.status)}">${esc(st.status)}${missing.length?' · missing '+esc(missing.join(', ')):''}${wfMissing?' · '+wfMissing+' workflow(s) missing':''}${wfInvalid?' · '+wfInvalid+' workflow(s) invalid':''}</div><div class="model-actions"><button class="mini-button install-model" data-model="${esc(m.id)}">Install missing</button><button class="mini-button remove-model" data-model="${esc(m.id)}">Remove weights</button></div><details class="workflow-details"><summary>Workflows (${(st.workflows||[]).length})</summary>${workflowRows||'<small>No workflows configured.</small>'}</details></div>`;
  }).join('')||'<span class="muted">No image models configured.</span>';
  const sel=$('#imageModel');const prev=sel.value;const sortedModels=[...(data.models||[])].sort((a,b)=>(b.priority||0)-(a.priority||0));sel.innerHTML='<option value="auto">Auto</option>'+sortedModels.map(m=>`<option value="${esc(m.id)}"${m.tagline?` title="${esc(m.tagline)}"`:''}>${esc(m.display_name||m.id)}</option>`).join(''); if([...sel.options].some(x=>x.value===prev))sel.value=prev;
  $('#imageInventory').innerHTML=(data.inventory||[]).map(x=>`<div>${esc(x.name)}<br><small>${esc(x.family)} · ${esc(x.size_gb)} GB</small></div>`).join('')||'<span class="muted">No local image weights discovered.</span>';
  renderSetup(data);
  $('#imageInstalls').innerHTML=(data.installs||[]).slice(0,8).map(j=>`<div class="install-row"><strong>${esc(j.model_id)}</strong><br><small>${esc(j.state)}${j.current_file?' · '+esc(j.current_file.split(/[\\/]/).pop()):''}${j.error?' · '+esc(j.error):''}</small><div class="bar"><span style="width:${Math.round((j.progress||0)*100)}%"></span></div></div>`).join('')||'<span class="muted">No model installs.</span>';
  renderLoras(data.loras||[]);
  $('#subjectProfiles').innerHTML=(data.profiles||[]).map(p=>`<div>${esc(p.display_name||p.id)}</div>`).join('')||'<span class="muted">No saved profiles.</span>';
  const ps=$('#subjectProfile');const pprev=ps.value;ps.innerHTML='<option value="">None</option>'+(data.profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.display_name||p.id)}</option>`).join('');if([...ps.options].some(x=>x.value===pprev))ps.value=pprev;
  renderJobs(data.jobs||[]);renderGallery(data.jobs||[]);updateComparison(data.jobs||[]);
}
function renderLoras(loras){
  const q=($('#loraFilter')?.value||'').trim().toLowerCase();
  const rows=loras.filter(l=>!q||[l.name,l.id,l.version,l.backend_name,...(l.tags||[]),...(l.compatible_families||[])].join(' ').toLowerCase().includes(q));
  $('#loraLibrary').innerHTML=rows.map(l=>`<div class="lora-row ${l.enabled?'':'disabled'}"><strong>${esc(l.name)}</strong><br><small>${esc(l.version||'unversioned')} · ${esc(l.size_gb)} GB · default ${esc(l.strength)}</small><br><small>${esc((l.compatible_families||[]).join(', ')||'compatibility not restricted')}</small><div class="lora-actions"><button class="mini-button use-lora" data-lora="${esc(l.id||l.backend_name)}" data-strength="${esc(l.strength)}">Use</button><button class="mini-button toggle-lora" data-path="${esc(l.path)}" data-enabled="${l.enabled?'1':'0'}">${l.enabled?'Disable':'Enable'}</button></div></div>`).join('')||'<span class="muted">No matching LoRAs installed.</span>';
}
function renderJobs(jobs){$('#imageJobs').innerHTML=jobs.slice(0,12).map(j=>{const message=j.error_message||j.error||'';const tech=j.technical_details?`<details class="technical-details"><summary>Technical details</summary><pre>${esc(j.technical_details)}</pre></details>`:'';return `<div class="image-job"><div><strong>${esc(j.operation||'image')}</strong> · ${esc(j.model_id||'')}</div><small>${esc(j.state)} · ${esc(j.stage||'')} ${message?'· '+esc(message):''}</small><div class="bar"><span style="width:${Math.round((j.progress||0)*100)}%"></span></div>${tech}${!['finished','failed','cancelled'].includes(j.state)?`<button class="mini-button cancel-job" data-job="${esc(j.id)}">Cancel</button>`:''}</div>`}).join('')||'<span class="muted">No image jobs yet.</span>';}
function renderGallery(jobs){const done=jobs.filter(j=>j.state==='finished'&&j.outputs?.length);$('#imageGallery').innerHTML=done.flatMap(j=>j.outputs.map(path=>`<div class="gallery-card"><img src="${pathUrl(j.id,path)}" alt="Generated image"><div class="meta"><strong>${esc(j.model_id)}</strong><br>${esc(j.request?.prompt||'').slice(0,120)}</div><div class="actions"><button class="mini-button use-source" data-src="${esc(path)}" data-job="${esc(j.id)}">Edit</button><button class="mini-button compare-job" data-src="${esc(path)}" data-job="${esc(j.id)}">Compare</button><button class="mini-button reuse-job" data-job="${esc(j.id)}">Reuse settings</button></div></div>`)).join('')||'<span class="muted">Finished images appear here.</span>';}
function renderRefs(){ $('#referenceStrip').innerHTML=refs.map((r,i)=>`<div class="reference-card"><img src="${r.preview}"><button class="mini-button" data-remove-ref="${i}">Remove</button></div>`).join('');setCompareImage('#beforeImage','#beforeEmpty',refs[0]?.preview||'');}
async function uploadFile(file){const data=await new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=fail;r.readAsDataURL(file);});const res=await fetch('/api/image/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,data_base64:data})});const out=await res.json();if(!res.ok)throw new Error(out.error||'Upload failed');refs.push({path:out.path,preview:data,name:file.name});renderRefs();if(refs.length===1)initMask(data);}
async function submit(){const prompt=$('#imagePrompt').value.trim();if(!prompt){$('#imageStatus').textContent='Describe what you want first.';return;}const rt=(((latest||{}).backend||{}).runtime)||{};if(rt.installed===false){$('#imageStatus').textContent='ComfyUI is not installed — press "Install everything" in the Backend panel.';speakLine('ComfyUI is not installed yet. Press Install everything in the Backend panel and I will set it all up for you.');return;}const operation=$('#imageOperation').value;if(operation==='inpaint'){if(maskDirty)await saveMask();if(!maskRef?.path){$('#imageStatus').textContent='Paint and save an inpainting mask first.';return;}}const [width,height]=$('#imageResolution').value.split('x').map(Number);const seed=$('#imageSeed').value;const body={prompt,operation,negative_prompt:$('#negativePrompt').value,width,height,count:Number($('#imageCount').value||1),seed:seed===''?null:Number(seed),quality:$('#imageQuality').value,reference_images:refs.map(r=>r.path),source_image:refs[0]?.path||'',mask_path:maskRef?.path||'',subject_profile:$('#subjectProfile').value,model_override:$('#imageModel').value,loras:parseLoras($('#loras').value),outpaint:parseKV($('#outpaint').value),transparent_background:$('#transparentBg').checked,upscale:$('#upscale').checked,refine_details:$('#refineDetails').checked,real_person:$('#realPerson').checked};const steps=$('#imageSteps').value,guidance=$('#imageGuidance').value,a=$('#imageStrength').value,d=$('#denoiseStrength').value;if(steps!=='')body.steps=Number(steps);if(guidance!=='')body.guidance=Number(guidance);if(a!=='')body.image_strength=Number(a);if(d!=='')body.denoise_strength=Number(d);$('#generateImage').disabled=true;$('#imageStatus').textContent='Queueing image job…';try{const res=await fetch('/api/image/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await res.json();if(!res.ok)throw new Error(out.error||'Image request failed');$('#imageStatus').textContent=`Queued ${out.job.id.slice(0,8)} using ${out.job.model_id}`;await load();}catch(e){$('#imageStatus').textContent=e.message;}finally{$('#generateImage').disabled=false;}}
$('#dropzone').addEventListener('click',()=>$('#imageFiles').click());$('#imageFiles').addEventListener('change',async e=>{for(const f of e.target.files)await uploadFile(f);e.target.value='';});['dragenter','dragover'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();$('#dropzone').classList.add('drag');}));['dragleave','drop'].forEach(ev=>$('#dropzone').addEventListener(ev,e=>{e.preventDefault();$('#dropzone').classList.remove('drag');}));$('#dropzone').addEventListener('drop',async e=>{for(const f of e.dataTransfer.files)if(f.type.startsWith('image/'))await uploadFile(f);});$('#referenceStrip').addEventListener('click',e=>{const b=e.target.closest('[data-remove-ref]');if(b){refs.splice(Number(b.dataset.removeRef),1);renderRefs();initMask(refs[0]?.preview||'');}});$('#generateImage').addEventListener('click',submit);$('#randomSeed').addEventListener('click',()=>{$('#imageSeed').value=Math.floor(Math.random()*2147483647)});$('#refreshImages').addEventListener('click',load);$('#imageJobs').addEventListener('click',async e=>{const b=e.target.closest('.cancel-job');if(!b)return;await fetch('/api/image/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:b.dataset.job})});load();});$('#imageGallery').addEventListener('click',e=>{const use=e.target.closest('.use-source'),compare=e.target.closest('.compare-job'),r=e.target.closest('.reuse-job');if(use){const path=use.dataset.src,jobId=use.dataset.job,preview=pathUrl(jobId,path);refs=[{path,preview,name:String(path).split(/[\\/]/).pop()}];renderRefs();initMask(preview);$('#imageOperation').value='edit_image';$('#imageStatus').textContent='Generated image loaded as the new source.';return;}if(compare){const path=compare.dataset.src,jobId=compare.dataset.job;setCompareImage('#beforeImage','#beforeEmpty',refs[0]?.preview||'');setCompareImage('#afterImage','#afterEmpty',pathUrl(jobId,path));return;}if(r){const j=(latest.jobs||[]).find(x=>x.id===r.dataset.job);if(j){const q=j.request||{};$('#imagePrompt').value=q.prompt||'';$('#negativePrompt').value=q.negative_prompt||'';$('#imageQuality').value=q.quality||'balanced';$('#imageModel').value=j.model_id||'auto';$('#imageSteps').value=q.steps??'';$('#imageGuidance').value=q.guidance??'';}}});
async function postJson(url,body={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}
let lastSetupKey='';
async function speakLine(t){try{if(window.NexusVoice&&NexusVoice.speak){await NexusVoice.speak(t);return;}const out=await postJson('/api/voice/speak',{text:t});if(out&&out.url)new Audio(out.url).play().catch(()=>{});}catch{}}
function renderSetup(data){
  const box=$('#imageSetup');if(!box)return;
  const setup=data.setup||{},rt=((data.backend||{}).runtime)||{};
  const installed=rt.installed!==false,st=setup.state||'idle',key=`${st}|${installed?'1':'0'}`;
  if(st==='installing_backend'||st==='installing_models'){
    const cj=setup.comfy_job||{};
    const phase=st==='installing_backend'?`Downloading ComfyUI · ${esc(String(cj.metadata?.phase||'starting'))} · ${Math.round((cj.progress||0)*100)}%`:'Downloading image models';
    const rows=(setup.models||[]).map(m=>`<div class="install-row"><strong>${esc(m.display_name)}</strong><br><small>${esc(m.state)}${m.current_file?' · '+esc(m.current_file.split(/[\\/]/).pop()):''}${m.error?' · '+esc(m.error):''}</small><div class="bar"><span style="width:${Math.round((m.progress||0)*100)}%"></span></div></div>`).join('');
    box.innerHTML=`<div class="setup-card"><strong>Setting up image generation</strong><small>${phase}</small><div class="bar"><span style="width:${Math.round((setup.progress||0)*100)}%"></span></div>${rows}</div>`;
    if(lastSetupKey!==key){lastSetupKey=key;if(st==='installing_backend')speakLine('Installing ComfyUI and the image models now. It is a large download, so this may take a while — I will let you know when it is ready.');}
    return;
  }
  if(st==='done'){box.innerHTML='';if(lastSetupKey!=='done'){lastSetupKey='done';$('#imageStatus').textContent='Image generation is ready — try your prompt again.';speakLine('All set — ComfyUI and the image models are installed. Give your prompt another try.');}return;}
  if(st==='failed'){box.innerHTML=`<div class="setup-card"><strong>Image setup failed</strong><small>${esc(setup.error||'unknown error')}</small><div class="button-row"><button class="mini-button" data-setup="start">Retry setup</button></div></div>`;lastSetupKey=key;return;}
  if(installed){box.innerHTML='';lastSetupKey=key;return;}
  box.innerHTML=`<div class="setup-card"><strong>ComfyUI required</strong><small>Image generation runs on a local ComfyUI engine, and it is not installed yet. Install ComfyUI plus all three image models now?</small><div class="button-row"><button class="mini-button" data-setup="start">Install everything</button><a class="mini-button" href="/tools.html?tool=comfyui">Install manually</a></div></div>`;
  if(lastSetupKey!=='offer'){lastSetupKey='offer';speakLine('Image generation needs ComfyUI — the local image engine — and it is not installed yet. I can install it together with all three image models. Just press Install on the Image page, or tell me to go ahead.');}
}
$('#imageSetup').addEventListener('click',async e=>{const b=e.target.closest('[data-setup]');if(!b)return;b.disabled=true;try{$('#imageStatus').textContent='Starting image setup…';await postJson('/api/image/setup',{});await load();}catch(err){$('#imageStatus').textContent=err.message;b.disabled=false;}});
$('#imageModels').addEventListener('click',async e=>{const install=e.target.closest('.install-model'),remove=e.target.closest('.remove-model'),imp=e.target.closest('.import-workflow');try{if(imp){pendingWorkflowImport={model_id:imp.dataset.model,operation:imp.dataset.operation};$('#workflowFile').value='';$('#workflowFile').click();return;}if(install){install.disabled=true;await postJson('/api/image/models/install',{model_id:install.dataset.model});$('#imageStatus').textContent=`Installing ${install.dataset.model}…`;await load();}if(remove){if(!confirm(`Remove installed weight files for ${remove.dataset.model}?`))return;remove.disabled=true;const d=await postJson('/api/image/models/remove',{model_id:remove.dataset.model});$('#imageStatus').textContent=`Removed ${d.removed.length} file(s).`;await load();}}catch(err){$('#imageStatus').textContent=err.message;}finally{if(install)install.disabled=false;if(remove)remove.disabled=false;}});
$('#workflowFile').addEventListener('change',async e=>{const file=e.target.files?.[0],target=pendingWorkflowImport;pendingWorkflowImport=null;if(!file||!target)return;try{$('#imageStatus').textContent=`Validating ${file.name} for ${target.model_id} / ${target.operation}…`;const text=await file.text();let workflow;try{workflow=JSON.parse(text);}catch{throw new Error('Workflow file is not valid JSON.');}const d=await postJson('/api/image/workflows/import',{...target,workflow});$('#imageStatus').textContent=`Imported ${d.workflow.name} (${d.workflow.node_count} API nodes).`;await load();}catch(err){$('#imageStatus').textContent=err.message;}finally{e.target.value='';}});
$('#maskPaint').addEventListener('click',()=>setMaskMode('paint'));
$('#maskErase').addEventListener('click',()=>setMaskMode('erase'));
$('#maskFill').addEventListener('click',()=>fillMask('white'));
$('#maskClear').addEventListener('click',()=>fillMask('black'));
$('#maskInvert').addEventListener('click',invertMask);
$('#saveMask').addEventListener('click',async()=>{try{await saveMask();$('#imageStatus').textContent='Mask saved locally.';}catch(e){$('#imageStatus').textContent=e.message;}});
$('#maskCanvas').addEventListener('pointerdown',e=>{if(!maskCtx)return;maskDrawing=true;$('#maskCanvas').setPointerCapture?.(e.pointerId);drawMask(e);});
$('#maskCanvas').addEventListener('pointermove',drawMask);
['pointerup','pointercancel','pointerleave'].forEach(name=>$('#maskCanvas').addEventListener(name,()=>{maskDrawing=false;}));
$('#loraFilter').addEventListener('input',()=>renderLoras(latest.loras||[]));
$('#loraLibrary').addEventListener('click',async e=>{const use=e.target.closest('.use-lora'),toggle=e.target.closest('.toggle-lora');try{if(use){const current=$('#loras').value.trim();const token=`${use.dataset.lora}:${use.dataset.strength||1}`;$('#loras').value=current?`${current}, ${token}`:token;$('#imageStatus').textContent=`Added LoRA ${use.dataset.lora}.`;}if(toggle){const enabled=toggle.dataset.enabled!=='1';await postJson('/api/image/loras/metadata',{path:toggle.dataset.path,metadata:{enabled}});$('#imageStatus').textContent=`LoRA ${enabled?'enabled':'disabled'}.`;await load();}}catch(err){$('#imageStatus').textContent=err.message;}});
$('#verifyImageModels').addEventListener('click',async()=>{try{$('#imageStatus').textContent='Verifying image models…';await postJson('/api/image/models/verify',{});await load();$('#imageStatus').textContent='Model verification complete.';}catch(e){$('#imageStatus').textContent=e.message;}});
$('#startImageBackend').addEventListener('click',async()=>{try{$('#imageStatus').textContent='Starting ComfyUI…';await postJson('/api/image/backend/start',{});await load();}catch(e){$('#imageStatus').textContent=e.message;}});
$('#stopImageBackend').addEventListener('click',async()=>{try{await postJson('/api/image/backend/stop',{});await load();}catch(e){$('#imageStatus').textContent=e.message;}});
load();setInterval(load,2500);
