const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderStats(data){const gh=data.github||{};const ghState=gh.api_enabled?(gh.authenticated?'GitHub API authenticated':'GitHub API public'):'GitHub web fallback';$('#researchStats').innerHTML=`${esc(data.cache_entries??0)} cached searches<br>${esc(data.sessions??0)} sessions<br><small>${esc(data.mode||'auto')} · TTL ${esc(data.ttl_hours??'?')}h<br>${esc(ghState)}</small>`;const recent=data.recent||data.sessions||[];if(Array.isArray(recent))$('#recentResearch').innerHTML=recent.length?recent.map(s=>`<div class="research-session"><strong>${esc((s.task||'').slice(0,70))}</strong><small>${esc(s.mode)} · ${esc(s.status)} · ${new Date((s.started_at||0)*1000).toLocaleString()}</small></div>`).join(''):'<span class="muted">No research sessions yet.</span>';}
function renderPlan(payload){const p=payload.plan||payload;const qs=(p.questions||[]).map(q=>`• ${esc(q.text)}${q.version_sensitive?'  [version-sensitive]':''}`).join('\n');const reasons=(p.reasons||[]).map(x=>`• ${esc(x)}`).join('\n');$('#researchPlan').innerHTML=`<strong>Mode:</strong> ${esc(p.mode)}<br><strong>Research needed:</strong> ${esc(p.needed)}<br><br><strong>Why</strong><br>${reasons||'No external gap detected.'}<br><br><strong>Questions</strong><br>${qs||'No research questions required.'}`;}
function renderSession(session){renderPlan(session.plan||{});$('#researchFindings').textContent=(session.summary||((session.findings||[]).join('\n'))||'No findings.');const sources=session.sources||[];$('#researchSources').innerHTML=sources.length?sources.map(s=>`<div class="source-row"><div class="source-head"><span class="source-title">${esc(s.title)}</span><span class="source-score">${esc(s.reliability)} · ${esc(s.score)}</span></div><div class="source-meta">${esc(s.source_type)} · version ${esc(s.version_relevance||'unknown')} · ${esc(s.provider||'')}</div>${s.url?`<div class="source-url"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.url)}</a></div>`:''}${s.excerpt?`<div class="source-excerpt">${esc(s.excerpt.slice(0,2500))}</div>`:''}</div>`).join(''):'<span class="muted">No sources found.</span>';}
async function refresh(){try{const data=await fetch('/api/research').then(r=>r.json());renderStats(data);}catch(e){$('#researchStats').textContent='Research API unavailable';}}
async function post(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await res.json();if(!res.ok)throw new Error(out.error||'Research request failed');return out;}
$('#planResearch').addEventListener('click',async()=>{const task=$('#researchQuery').value.trim();if(!task)return;$('#researchStatus').textContent='Inspecting repository and environment…';try{const out=await post('/api/research/plan',{task,mode:$('#researchMode').value});renderPlan(out);$('#researchFindings').textContent=out.guidance||'Plan ready.';$('#researchStatus').textContent='Plan complete. No web request was made.';}catch(e){$('#researchStatus').textContent=e.message;}});
$('#runResearch').addEventListener('click',async()=>{const query=$('#researchQuery').value.trim();if(!query)return;const b=$('#runResearch');b.disabled=true;$('#researchStatus').textContent='Researching authoritative sources…';try{const out=await post('/api/research/run',{query,mode:$('#researchMode').value,version:$('#researchVersion').value.trim()});renderSession(out.session);$('#researchStatus').textContent=`${out.session.status} · ${(out.session.sources||[]).length} sources`;await refresh();}catch(e){$('#researchStatus').textContent=e.message;}finally{b.disabled=false;}});
refresh();
